### ISSUE TITLE
Use `URLSearchParams` instead of old regex implementation for `core.parameter`

### ISSUE THREAD

**Issue by sd0e** [LiveGTech/Adapt-UI#3]

**Comment by James-Livesey** [comment]
wow you really had to add all the labels lol

**Comment by James-Livesey** [comment]
that's better

**Comment by James-Livesey** [comment]
and a better title too

**Comment by James-Livesey** [comment]
I'll unassign myself in case anyone else wants to do this, I mean it's not that hard (ensure to `decodeURIComponent` :wink: too) and not too critical, but would be nice to have!
